args <- commandArgs(trailingOnly=TRUE); stopifnot(length(args)==2)
root <- normalizePath(args[1],winslash='/'); data_root <- normalizePath(args[2],winslash='/')
.libPaths(c(file.path(data_root,'analysis/corrections/statistics/.tools/R-library'),.libPaths()))
suppressPackageStartupMessages(library(edgeR))
source(file.path(root,'RQ_Specified/A5_A11_shared_component_contract/scripts/paired_inference.R'))
here <- file.path(root,'RQ_Specified/A11_lesion_programme_addition'); out <- file.path(here,'tables/test_v2')
if(file.exists(file.path(out,'inference.tsv'))) stop('Refusing to overwrite Kim scores')
stopifnot(file.exists(file.path(out,'prepare_run.json')))
check <- read.delim(file.path(out,'instrument_check.tsv')); stopifnot(nrow(check)==46,max(check$abs_error)<=1e-6)
x <- as.matrix(read.delim(gzfile(file.path(here,'cache/test_v2/counts.tsv.gz')),row.names=1,check.names=FALSE))
m <- read.delim(file.path(out,'units.tsv')); stopifnot(identical(colnames(x),m$unit_id))
y <- calcNormFactors(DGEList(counts=x),method='TMM'); lc <- cpm(y,log=TRUE,prior.count=1)
g <- read.delim(file.path(out,'human_module_genes.tsv')); modules <- split(g$gene,g$module)
rows <- list(); pairs <- list()
for(k in names(modules)) {
  v <- colMeans(lc[modules[[k]],,drop=FALSE])
  rows[[length(rows)+1]] <- cbind(m,module=k,score=unname(v))
  for(p in unique(m$patient)) {
    a <- which(m$patient==p & m$arm=='lesion'); b <- which(m$patient==p & m$arm=='normal')
    stopifnot(length(a)==1,length(b)==1)
    pairs[[length(pairs)+1]] <- data.frame(patient=p,module=k,difference=unname(v[a]-v[b]))
  }
}
z <- do.call(rbind,pairs)
getd <- function(k) { q <- z[z$module==k,]; setNames(q$difference,q$patient) }
d <- getd('lesion_specific'); sh <- getd('shared_remodelling')
tests <- list(primary=d,beyond_shared=d-sh[names(d)],stress_excluded=getd('stress_excluded'),injury_lesion_pair=getd('injury_lesion_pair'))
res <- do.call(rbind,lapply(names(tests),function(k)cbind(test=k,location_test(tests[[k]]))))
res$q_secondary <- NA_real_; res$q_secondary[-1] <- p.adjust(ifelse(is.finite(res$p_exact[-1]),res$p_exact[-1],1),'BH')
write.table(res,file.path(out,'inference.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
write.table(z,file.path(out,'paired_differences.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
write.table(do.call(rbind,rows),file.path(out,'scores.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
write.table(cbind(m,library_size=y$samples$lib.size,TMM_factor=y$samples$norm.factors),file.path(out,'normalization.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
loo <- data.frame(omitted_patient=names(d),remaining_n=length(d)-1,remaining_mean=sapply(seq_along(d),function(j)mean(d[-j])))
write.table(loo,file.path(out,'omission_diagnostics.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
capture.output(sessionInfo(),file=file.path(out,'R_session.txt'))
print(res[,c('test','n','mean','HL','low','high','p_exact','q_secondary','direction','magnitude')],row.names=FALSE)
